import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import StyledComponentsProvider from '@/libs/styledComponents/Provider'
import Navigation from '@/components/Navigation'
import Wrapper from '@/components/Wrapper'
import TopBar from '@/components/atom/TopBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsProvider>
          <TopBar />
          <Navigation />
          <Wrapper>{children}</Wrapper>
        </StyledComponentsProvider>
      </body>
    </html>
  )
}
