import type { Metadata } from 'next'
import StyledComponentsProvider from '@/libs/styledComponents/Provider'
import Navigation from '@/components/Molecules/Navigation'
import Wrapper from '@/components/Wrapper'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsProvider>
          <Navigation />
          <Wrapper>{children}</Wrapper>
        </StyledComponentsProvider>
      </body>
    </html>
  )
}
